# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84c49b912fb1ceac037e6fab840bc398"
name = "CountDown"
application_url = "https://countdown-theta-ashen.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "countdown2-2.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [ "https://countdown-theta-ashen.vercel.app/auth/callback" ]

[app_proxy]
url = "https://countdown-theta-ashen.vercel.app/apps/timer"
subpath = "timer"
prefix = "apps"
